# Generated by Django 4.2.16 on 2024-11-28 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('photo', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ManyToManyField(blank=True, related_name='spacethings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
